---
apiVersion: apps/v1
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web-server-naz1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-server-naz1
  template:
    metadata:
      labels:
        app: web-server-naz1
    spec:
      containers:
        - name: web-server-containers
          image: 937382548142.dkr.ecr.ap-south-1.amazonaws.com/myecr:latest
