---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pro
  template:
    metadata:
      labels:
        app: pro
    spec:
      containers:
        - name: product-containers
          image: 937382548142.dkr.ecr.ap-south-1.amazonaws.com/pro:latest
