---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pro1
spec:
  replicas: 0
  selector:
    matchLabels:
      app: pro1
  template:
    metadata:
      labels:
        app: pro1
    spec:
      containers:
        - name: web-server-containers
          image: 937382548142.dkr.ecr.ap-south-1.amazonaws.com/pro:latest
